# Generated by Django 6.0.8 on 2026-08-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='target_process',
            new_name='target_progress',
        ),
    ]
