# Generated by Django 6.0.8 on 2026-08-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_rename_target_process_goal_target_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
