# Generated by Django 6.0.8 on 2026-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='completd',
        ),
        migrations.AddField(
            model_name='milestone',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
