# Generated by Django 6.0.8 on 2026-08-09 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_remove_milestone_completd_milestone_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('MILESTONE_CREATED', 'Milestone Created'), ('MILESTONE_COMPLETED', 'Milestone Completed'), ('MILESTONE_UNDONE', 'Milestone Undone'), ('MILESTONE_UPDATED', 'Milestone Updated'), ('MILESTONE_DELETED', 'Milestone Deleted')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='skills.project')),
            ],
        ),
    ]
