# Generated by Django 6.0.8 on 2026-08-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_goaltask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
