# Generated by Django 6.0.8 on 2026-08-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='user',
        ),
        migrations.AddField(
            model_name='challenge',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='skills.skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
    ]
