# Generated by Django 6.0.8 on 2026-08-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0021_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='skills.challenge'),
        ),
        migrations.AddField(
            model_name='activity',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='skills.note'),
        ),
        migrations.AddField(
            model_name='activity',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='skills.roadmap'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('MILESTONE_CREATED', 'Milestone Created'), ('MILESTONE_COMPLETED', 'Milestone Completed'), ('MILESTONE_UNDONE', 'Milestone Undone'), ('MILESTONE_UPDATED', 'Milestone Updated'), ('MILESTONE_DELETED', 'Milestone Deleted'), ('ROADMAP_CREATED', 'Roadmap Created'), ('ROADMAP_UPDATED', 'Roadmap Updated'), ('ROADMAP_DELETED', 'Roadmap Deleted'), ('ROADMAP_STEP_CREATED', 'Roadmap Step Created'), ('ROADMAP_STEP_COMPLETED', 'Roadmap Step Completed'), ('ROADMAP_STEP_UNDONE', 'Roadmap Step Undone'), ('ROADMAP_STEP_UPDATED', 'Roadmap Step Updated'), ('ROADMAP_STEP_DELETED', 'Roadmap Step Deleted'), ('CHALLENGE_CREATED', 'Challenge Created'), ('CHALLENGE_UPDATED', 'Challenge Updated'), ('CHALLENGE_COMPLETED', 'Challenge Completed'), ('CHALLENGE_UNDONE', 'Challenge Undone'), ('CHALLENGE_DELETED', 'Challenge Deleted'), ('NOTE_CREATED', 'Note Created'), ('NOTE_UPDATED', 'Note Updated'), ('NOTE_DELETED', 'Note Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='skills.project'),
        ),
    ]
