# Generated by Django 6.0.8 on 2026-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0022_activity_challenge_activity_note_activity_roadmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('MILESTONE_CREATED', 'Milestone Created'), ('MILESTONE_COMPLETED', 'Milestone Completed'), ('MILESTONE_UNDONE', 'Milestone Undone'), ('MILESTONE_UPDATED', 'Milestone Updated'), ('MILESTONE_DELETED', 'Milestone Deleted'), ('ROADMAP_CREATED', 'Roadmap Created'), ('ROADMAP_UPDATED', 'Roadmap Updated'), ('ROADMAP_DELETED', 'Roadmap Deleted'), ('ROADMAP_STEP_CREATED', 'Roadmap Step Created'), ('ROADMAP_STEP_UPDATED', 'Roadmap Step Updated'), ('ROADMAP_STEP_COMPLETED', 'Roadmap Step Completed'), ('ROADMAP_STEP_UNDONE', 'Roadmap Step Undone'), ('ROADMAP_STEP_DELETED', 'Roadmap Step Deleted'), ('CHALLENGE_CREATED', 'Challenge Created'), ('CHALLENGE_UPDATED', 'Challenge Updated'), ('CHALLENGE_DELETED', 'Challenge Deleted'), ('CHALLENGE_COMPLETED', 'Challenge Completed'), ('CHALLENGE_UNDONE', 'Challenge Undone'), ('NOTE_CREATED', 'Note Created'), ('NOTE_UPDATED', 'Note Updated'), ('NOTE_DELETED', 'Note Deleted')], max_length=40),
        ),
    ]
