# Generated by Django 6.0.8 on 2026-08-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0023_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
