# Generated by Django 6.0.8 on 2026-08-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0024_project_resource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
